server:
  port: 8001
eureka:
  instance:
    hostname: mspersons.cfs6q686kbf1.us-east-2.rds.amazonaws.com
  client:
    service-url:
      #      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: persons-microservice
  datasource:
    url: jdbc:postgresql://mspersons.cfs6q686kbf1.us-east-2.rds.amazonaws.com:5432/MsPersons
    username: postgres
    password: 12345678A
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
logging:
  level:
    org.springframework.cloud.gateway: debug
